#!/bin/bash
echo "Configuring network interface for the motor controller"
echo "IP_ADDR=192.6.94.1"
ip addr add 192.6.94.1/24 dev enp20s0

echo "Stopping client LDAP service"
systemctl stop nslcd

touch /tmp/niklas
