#!/bin/bash
echo "Configuring network interface for the motor controller"
echo "IP_ADDR=192.6.94.1"
nmcli connection add type ethernet con-name GEOBRICK ifname enp20s0 ip4 192.6.94.1/24
nmcli connection up GEOBRICK

echo "Stopping client LDAP service"
systemctl stop nslcd

echo "Adding the default route"
ip route add default via 192.168.10.1

touch /tmp/konrad
